;; GENERATED by tools/gen_shot_table.py. Do not edit; rerun the script.
;; 64 directions, (dx, dy) 8.8 per power unit; +y is down the screen.
.module game_shot_table

.area _CODE

shot_directions::
    .dw    39,     0    ;;   0 deg
    .dw    39,     6    ;;   5 deg
    .dw    38,    12    ;;  11 deg
    .dw    37,    19    ;;  16 deg
    .dw    36,    24    ;;  22 deg
    .dw    34,    30    ;;  28 deg
    .dw    32,    36    ;;  33 deg
    .dw    30,    41    ;;  39 deg
    .dw    27,    45    ;;  45 deg
    .dw    25,    49    ;;  50 deg
    .dw    22,    53    ;;  56 deg
    .dw    18,    56    ;;  61 deg
    .dw    15,    59    ;;  67 deg
    .dw    11,    61    ;;  73 deg
    .dw     8,    63    ;;  78 deg
    .dw     4,    64    ;;  84 deg
    .dw     0,    64    ;;  90 deg
    .dw    -4,    64    ;;  95 deg
    .dw    -8,    63    ;; 101 deg
    .dw   -11,    61    ;; 106 deg
    .dw   -15,    59    ;; 112 deg
    .dw   -18,    56    ;; 118 deg
    .dw   -22,    53    ;; 123 deg
    .dw   -25,    49    ;; 129 deg
    .dw   -27,    45    ;; 135 deg
    .dw   -30,    41    ;; 140 deg
    .dw   -32,    36    ;; 146 deg
    .dw   -34,    30    ;; 151 deg
    .dw   -36,    24    ;; 157 deg
    .dw   -37,    19    ;; 163 deg
    .dw   -38,    12    ;; 168 deg
    .dw   -39,     6    ;; 174 deg
    .dw   -39,     0    ;; 180 deg
    .dw   -39,    -6    ;; 185 deg
    .dw   -38,   -12    ;; 191 deg
    .dw   -37,   -19    ;; 196 deg
    .dw   -36,   -24    ;; 202 deg
    .dw   -34,   -30    ;; 208 deg
    .dw   -32,   -36    ;; 213 deg
    .dw   -30,   -41    ;; 219 deg
    .dw   -27,   -45    ;; 225 deg
    .dw   -25,   -49    ;; 230 deg
    .dw   -22,   -53    ;; 236 deg
    .dw   -18,   -56    ;; 241 deg
    .dw   -15,   -59    ;; 247 deg
    .dw   -11,   -61    ;; 253 deg
    .dw    -8,   -63    ;; 258 deg
    .dw    -4,   -64    ;; 264 deg
    .dw     0,   -64    ;; 270 deg
    .dw     4,   -64    ;; 275 deg
    .dw     8,   -63    ;; 281 deg
    .dw    11,   -61    ;; 286 deg
    .dw    15,   -59    ;; 292 deg
    .dw    18,   -56    ;; 298 deg
    .dw    22,   -53    ;; 303 deg
    .dw    25,   -49    ;; 309 deg
    .dw    27,   -45    ;; 315 deg
    .dw    30,   -41    ;; 320 deg
    .dw    32,   -36    ;; 326 deg
    .dw    34,   -30    ;; 331 deg
    .dw    36,   -24    ;; 337 deg
    .dw    37,   -19    ;; 343 deg
    .dw    38,   -12    ;; 348 deg
    .dw    39,    -6    ;; 354 deg
