;; GENERATED by tools/gen_ball_blit.py. Do not edit; rerun the script.
;; Ball shape (6x8):
;;   .XXXX.
;;   XXXXXX
;;   XXXXXX
;;   XXXXXX
;;   XXXXXX
;;   XXXXXX
;;   XXXXXX
;;   .XXXX.
.module sys_ball_blit

.area _CODE

;;-----------------------------------------------------------------
;;
;; sys_ball_blit_draw
;;
;;  Input: HL = video pointer to the shape's top-left byte,
;;         B = full pattern, C = l pattern, D = r pattern (E unused --
;;         this shape has no fully-felt byte inside its bounding box)
;;  Output:
;;  Modified: AF, HL
;;
sys_ball_blit_draw::
    ld (hl), c
    inc hl
    ld (hl), b
    inc hl
    ld (hl), d
    ld a, h
    add a, #8
    ld h, a
    and #0x38
    jr nz, sys_ball_blit_draw_skip_wrap_0
    ld a, l
    add a, #0x50
    ld l, a
    ld a, h
    adc a, #0xC0
    ld h, a
sys_ball_blit_draw_skip_wrap_0:
    ld (hl), b
    dec hl
    ld (hl), b
    dec hl
    ld (hl), b
    ld a, h
    add a, #8
    ld h, a
    and #0x38
    jr nz, sys_ball_blit_draw_skip_wrap_1
    ld a, l
    add a, #0x50
    ld l, a
    ld a, h
    adc a, #0xC0
    ld h, a
sys_ball_blit_draw_skip_wrap_1:
    ld (hl), b
    inc hl
    ld (hl), b
    inc hl
    ld (hl), b
    ld a, h
    add a, #8
    ld h, a
    and #0x38
    jr nz, sys_ball_blit_draw_skip_wrap_2
    ld a, l
    add a, #0x50
    ld l, a
    ld a, h
    adc a, #0xC0
    ld h, a
sys_ball_blit_draw_skip_wrap_2:
    ld (hl), b
    dec hl
    ld (hl), b
    dec hl
    ld (hl), b
    ld a, h
    add a, #8
    ld h, a
    and #0x38
    jr nz, sys_ball_blit_draw_skip_wrap_3
    ld a, l
    add a, #0x50
    ld l, a
    ld a, h
    adc a, #0xC0
    ld h, a
sys_ball_blit_draw_skip_wrap_3:
    ld (hl), b
    inc hl
    ld (hl), b
    inc hl
    ld (hl), b
    ld a, h
    add a, #8
    ld h, a
    and #0x38
    jr nz, sys_ball_blit_draw_skip_wrap_4
    ld a, l
    add a, #0x50
    ld l, a
    ld a, h
    adc a, #0xC0
    ld h, a
sys_ball_blit_draw_skip_wrap_4:
    ld (hl), b
    dec hl
    ld (hl), b
    dec hl
    ld (hl), b
    ld a, h
    add a, #8
    ld h, a
    and #0x38
    jr nz, sys_ball_blit_draw_skip_wrap_5
    ld a, l
    add a, #0x50
    ld l, a
    ld a, h
    adc a, #0xC0
    ld h, a
sys_ball_blit_draw_skip_wrap_5:
    ld (hl), b
    inc hl
    ld (hl), b
    inc hl
    ld (hl), b
    ld a, h
    add a, #8
    ld h, a
    and #0x38
    jr nz, sys_ball_blit_draw_skip_wrap_6
    ld a, l
    add a, #0x50
    ld l, a
    ld a, h
    adc a, #0xC0
    ld h, a
sys_ball_blit_draw_skip_wrap_6:
    ld (hl), d
    dec hl
    ld (hl), b
    dec hl
    ld (hl), c
    ret

;;-----------------------------------------------------------------
;;
;; sys_ball_blit_erase
;;
;;  Input: HL = video pointer to the shape's top-left byte,
;;         E = felt pattern (B/C/D unused)
;;  Output:
;;  Modified: AF, HL
;;
sys_ball_blit_erase::
    ld (hl), e
    inc hl
    ld (hl), e
    inc hl
    ld (hl), e
    ld a, h
    add a, #8
    ld h, a
    and #0x38
    jr nz, sys_ball_blit_erase_skip_wrap_0
    ld a, l
    add a, #0x50
    ld l, a
    ld a, h
    adc a, #0xC0
    ld h, a
sys_ball_blit_erase_skip_wrap_0:
    ld (hl), e
    dec hl
    ld (hl), e
    dec hl
    ld (hl), e
    ld a, h
    add a, #8
    ld h, a
    and #0x38
    jr nz, sys_ball_blit_erase_skip_wrap_1
    ld a, l
    add a, #0x50
    ld l, a
    ld a, h
    adc a, #0xC0
    ld h, a
sys_ball_blit_erase_skip_wrap_1:
    ld (hl), e
    inc hl
    ld (hl), e
    inc hl
    ld (hl), e
    ld a, h
    add a, #8
    ld h, a
    and #0x38
    jr nz, sys_ball_blit_erase_skip_wrap_2
    ld a, l
    add a, #0x50
    ld l, a
    ld a, h
    adc a, #0xC0
    ld h, a
sys_ball_blit_erase_skip_wrap_2:
    ld (hl), e
    dec hl
    ld (hl), e
    dec hl
    ld (hl), e
    ld a, h
    add a, #8
    ld h, a
    and #0x38
    jr nz, sys_ball_blit_erase_skip_wrap_3
    ld a, l
    add a, #0x50
    ld l, a
    ld a, h
    adc a, #0xC0
    ld h, a
sys_ball_blit_erase_skip_wrap_3:
    ld (hl), e
    inc hl
    ld (hl), e
    inc hl
    ld (hl), e
    ld a, h
    add a, #8
    ld h, a
    and #0x38
    jr nz, sys_ball_blit_erase_skip_wrap_4
    ld a, l
    add a, #0x50
    ld l, a
    ld a, h
    adc a, #0xC0
    ld h, a
sys_ball_blit_erase_skip_wrap_4:
    ld (hl), e
    dec hl
    ld (hl), e
    dec hl
    ld (hl), e
    ld a, h
    add a, #8
    ld h, a
    and #0x38
    jr nz, sys_ball_blit_erase_skip_wrap_5
    ld a, l
    add a, #0x50
    ld l, a
    ld a, h
    adc a, #0xC0
    ld h, a
sys_ball_blit_erase_skip_wrap_5:
    ld (hl), e
    inc hl
    ld (hl), e
    inc hl
    ld (hl), e
    ld a, h
    add a, #8
    ld h, a
    and #0x38
    jr nz, sys_ball_blit_erase_skip_wrap_6
    ld a, l
    add a, #0x50
    ld l, a
    ld a, h
    adc a, #0xC0
    ld h, a
sys_ball_blit_erase_skip_wrap_6:
    ld (hl), e
    dec hl
    ld (hl), e
    dec hl
    ld (hl), e
    ret
