#!/usr/bin/env python3
"""Generate src/sys/row_table.s: one screen address per felt scanline.

CPC mode-0 screen address formula (cpct_getScreenPtr_asm's own): for byte-x
X and pixel-y Y, addr = 0xC000 + 80*(Y//8) + 2048*(Y&7) + X. This table
holds addr(X=0, Y) for every felt scanline (Y = TABLE_Y_PX..TABLE_Y_PX+
TABLE_HEIGHT_PX-1), so sys/entity.s's draw path can look up "start of this
row" with one table read instead of cpct_getScreenPtr_asm's runtime
divide/shift chain -- the row a ball is drawn on is a compile-time-unknown
but easily table-indexed value (row - TABLE_Y_PX), never a value the Z80
needs to compute from scratch every frame.

Usage: python3 tools/gen_row_table.py > src/sys/row_table.s
"""
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parent.parent


def config(name):
    text = (ROOT / "src" / "config.h.s").read_text()
    return int(re.search(rf"^\s*{name}\s*=\s*(\d+)", text, re.M).group(1))


def row_addr(y):
    return 0xC000 + 80 * (y // 8) + 2048 * (y & 7)


def main():
    table_y = config("TABLE_Y_PX")
    table_h = config("TABLE_HEIGHT_PX")

    print(";; GENERATED by tools/gen_row_table.py. Do not edit; rerun the script.")
    print(f";; {table_h} entries, felt_row_addr[y - {table_y}] = screen address of")
    print(f";; (x_byte=0, y={table_y}..{table_y + table_h - 1}). See sys/entity.s.")
    print(".module sys_row_table")
    print()
    print(".area _CODE")
    print()
    print("felt_row_addr::")
    for y in range(table_y, table_y + table_h):
        print(f"    .dw 0x{row_addr(y):04X}    ;; y={y}")


if __name__ == "__main__":
    main()
