#!/usr/bin/env python3
"""Generate src/game/shot_table.s: 32 shot directions as 8.8 velocity steps.

Each entry is (dx, dy) for a speed of STEP raster lines per frame. Mode 0
pixels are wider than tall: the 160x132 felt looks 2:1, so one pixel spans
2*132/160 = 1.65 line heights. dx is divided by that ratio so every direction
moves the same distance on screen. game/shot.s multiplies an entry by a random
power, so the table only fixes the direction.

Usage: python3 tools/gen_shot_table.py > src/game/shot_table.s
"""
import math

DIRECTIONS = 32
STEP = 64                 # 8.8: 0.25 raster lines per frame per power unit
PIXEL_ASPECT = 2 * 132 / 160


def entries():
    for i in range(DIRECTIONS):
        angle = 2 * math.pi * i / DIRECTIONS
        yield round(math.cos(angle) * STEP / PIXEL_ASPECT), round(math.sin(angle) * STEP)


def main():
    print(";; GENERATED by tools/gen_shot_table.py. Do not edit; rerun the script.")
    print(f";; {DIRECTIONS} directions, (dx, dy) 8.8 per power unit; +y is down the screen.")
    print(".module game_shot_table")
    print()
    print(".area _CODE")
    print()
    print("shot_directions::")
    for i, (dx, dy) in enumerate(entries()):
        print(f"    .dw {dx:5d}, {dy:5d}    ;; {i * 360 // DIRECTIONS:3d} deg")


if __name__ == "__main__":
    main()
